package de.qaware.ekg.awb.importer.owidcovidonline.bl;

import de.qaware.ekg.awb.sdk.datamodel.TimeSeries;
import de.qaware.ekg.awb.sdk.testsupport.LocalImportStrategyRunner;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * This is an sample unit test for the (Local)ImportStrategy generated by the SDK archetype.
 */
public class OwidCovidOnlineImportStrategyTest {
    private static final String SAMPLE_FILE = "testdata/sample.csv";

    @Test
    public void testStrategy() {
        LocalImportStrategyRunner runner = LocalImportStrategyRunner.newBuilder()
                .strategyToTest(new OwidCovidOnlineImportStrategy(List.of(
                        ClassLoader.getSystemResource(SAMPLE_FILE).getFile()
                )))
                .activateRemoteSolrExport() // exports the data proceed by the strategy to an standalone Solr instance
                .useProject("myTestProject") // assign the data in the remote Solr the this project
                .build();


        List<TimeSeries> seriesData = runner.runStrategy();
        assertThat(seriesData.size()).isEqualTo(7844);
    }
}
